server:
  port : 8762

eureka:
  instance:
    hostname: eureka-zone2
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    evictionIntervalTimerInMs: 50000
  datacenter: onepieceDataCenter
  availabilityZones:
    onepieceDataCenter: zone1,zone2
