server:
  port : 8761

eureka:
  instance:
    hostname: eureka-zone1
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  server:
    evictionIntervalTimerInMs: 50000
  datacenter: onepieceDataCenter
  availabilityZones:
    onepieceDataCenter: zone1,zone2
