server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE  # Load balancing via Eureka
          predicates:
            - Path=/accounts/**
        - id: customer-service
          uri: lb://CUSTOMER-SERVICE # Load balancing via Eureka
          predicates:
            - Path=/customers/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true  # Fetch service list from Eureka
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka Server URL

springdoc:
  swagger-ui:
    urls:
      - name: Account Service
        url: /account/v3/api-docs
      - name: Customer Service
        url: /customer/v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: "*"