server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: http://localhost:8080
          predicates:
            - Path=/accounts/**
        - id: customer-service
          uri: http://localhost:8081
          predicates:
            - Path=/customers/**

springdoc:
  swagger-ui:
    urls:
      - name: Account Service
        url: /account/v3/api-docs
      - name: Customer Service
        url: /customer/v3/api-docs
